name = "matchday-ledger-api"
main = "worker/index.js"
compatibility_date = "2025-04-01"
workers_dev = true

[vars]
API_VERSION = "v1"

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "FOOTBALL_CACHE"
id = "9b3eddcb31a842b3bb1848635c15bca4"
